### ISSUE TITLE
prometheus: serviceMonitorSelector can't be evaluated

### ISSUE THREAD

**Issue by tsutsarin-fuib** [cloudposse/charts#114]
When running the following `values.yaml`:

```yaml

serviceMonitors:
  - name: frontend-chart
    selector:
      matchLabels:
        tier: frontend-chart
    endpoints:
    - port: prometheus
      interval: 5s

serviceMonitorsSelector:
  matchLabels:
    tier: frontend-chart
```
I'm getting an error:
```
$ helm install --dry-run --debug -f values.yaml cloudposse-incubator/prometheus
...
Error: render error in "prometheus/templates/servicemonitors.yaml": template: prometheus/templates/servicemonitors.yaml:19:17: executing "prometheus/templates/servicemonitors.yaml" at <.Values.serviceMonit...>: can't evaluate field serviceMonitorSelector in type interface {}
```
What is proper use of `serviceMonitors` and `serviceMonitorsSelector` parameters?

There are some suspicious lines in [`servicemonitors.yaml`](https://github.com/cloudposse/charts/blob/9cfa7239fcfd608f7d8550f35156e85ad7493786/incubator/prometheus/templates/servicemonitors.yaml#L19) template:
- `serviceMonitorSelector` chart paramater applies the same for each monitor in the list of service monitors
- There could be wrong indentation in `name: {{ .name }}` line
- There are `.Values.serviceMonitorsSelector` in `prometheus.yaml` and `.Values.serviceMonitorSelector` in `servicemonitors.yaml`, note the monitor word plurality, is it intended to have two almost identical parameters?

**Comment by bradbeam** [comment]
ServiceMonitors are a third party resource created by the prometheus operator. I think the kube-prometheus chart needs to be updated to deploy prometheus-operator instead of just prometheus.

**Comment by tsutsarin-fuib** [comment]
@bradbeam, I have prometheus-operator already deployed.
The problem is with `cloudposse-incubator/prometheus`, which deploys Prometheus instance as Prometheus TPR along with ServiceMonitor TPR.

**Comment by goruha** [comment]
@tsutsarin-fuib I found issue. 
You are right about bug.
Will make quick fix.

**Comment by goruha** [comment]
@tsutsarin-fuib 
Fixed in #115

**Comment by goruha** [comment]
Right values.yaml

```yaml
serviceMonitors:
  - name: frontend-chart
    namespaceSelector:
      any: true
    selector:
      matchLabels:
        tier: frontend-chart
    endpoints:
    - port: prometheus
      interval: 5s

serviceMonitorsSelector:
  tier: frontend-chart
```
