### ISSUE TITLE
"coalesce.go:165: warning: skipped value for ..." when installing monochart

### ISSUE THREAD

**Issue by tstmrk** [cloudposse/charts#233]
When I try to install or template monochart I get the following errors

```
coalesce.go:165: warning: skipped value for configMaps: Not a table.
coalesce.go:165: warning: skipped value for secrets: Not a table.
coalesce.go:165: warning: skipped value for env: Not a table.
coalesce.go:165: warning: skipped value for env: Not a table.
coalesce.go:165: warning: skipped value for secrets: Not a table.
coalesce.go:165: warning: skipped value for configMaps: Not a table.
```

The command that I use is:
```
helm template ./monochart --values ./monochart/values.example.yaml
```

This is the result:
```
---
# Source: monochart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-monochart-env-default
  annotations:
    test.secret.annotation: value
  labels:
    app: monochart
    chart: monochart-0.19.1
    heritage: "Helm"
    raar: env
    test_label: value
type: Opaque
data:
  SECRET_ENV_NAME: RU5WX1ZBTFVF
---
# Source: monochart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-monochart-env-default
  annotations:
    test.annotation: value
  labels:
    app: monochart
    chart: monochart-0.19.1
    heritage: "Helm"
    component: env
    test_label: value
data:
  CONFIG_ENV_NAME: ENV_VALUE
---
# Source: monochart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-monochart-files-default
  annotations:
    test.annotation: value
  labels:
    app: monochart
    chart: monochart-0.19.1
    heritage: "Helm"
    component: files
    test_label: value
data:
  config.test.txt: |
    some text
---
# Source: monochart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: release-name-monochart
  annotations:
    nginx.version: 1.15.3
  labels:
    app: monochart
    chart: monochart-0.19.1
    heritage: "Helm"
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monochart
      release: RELEASE-NAME
  revisionHistoryLimit: 10
  template:
    metadata:
      name: release-name-monochart
      annotations:
        checksum/config: 165a67949dac02dddcf221cc922cb694be98da09218747ed7c729408cd1c4422
        checksum/secret: b5fe613c0d2ad6de7de9f011f86295346d5e7c78e2bd212b83303113f9f39749
      labels:
        app: monochart
        release: "RELEASE-NAME"
        serve: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - monochart
                - key: release
                  operator: In
                  values:
                  - "RELEASE-NAME"
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - postgresql
              - key: bla
                operator: In
                values:
                - bla-postgresql
            topologyKey: kubernetes.io/hostname
      containers:
      - name: RELEASE-NAME
        image: nginx:1.15.3
        imagePullPolicy: IfNotPresent
        
        envFrom:
        - configMapRef:
            name: release-name-monochart-env-default
        - secretRef:
            name: release-name-monochart-env-default
        env:
          - name: INLINE_ENV_NAME
            value: "ENV_VALUE"
        envFrom:
          - configMapRef:
              name: config-1
          - configMapRef:
              name: config-2
        ports:
          - name: default
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - mountPath: "/data"
          name: storage
        
        - mountPath: /config-default
          name: config-default-files
        - mountPath: /secret-default
          name: secret-default-files
          readOnly: true
      imagePullSecrets:
        - name: docker-secret-1
        - name: docker-secret-2
      volumes:
      - name: storage
        emptyDir: {}
      
      - name: config-default-files
        configMap:
          name: release-name-monochart-files-default
      - name: secret-default-files
        secret:
          secretName: release-name-monochart-files-default
```

It seems that the configMaps are generated, but not all the secrets.
