### ISSUE TITLE
{{ requiredEnv "RELEASE_NAME" }} used in the file values.example.yaml in monochart

### ISSUE THREAD

**Issue by tstmrk** [cloudposse/charts#234]
`{{ requiredEnv "RELEASE_NAME" }}` used in the file values.example.yam in monochartl, but I think this is typically a Helmfile-thing and can't be used in a Helm values file.

```
[...]
  affinity:
    # use of simple rule
    affinityRule: "ShouldBeOnDifferentNode"
    # use custom affinity rule. Here app MUST be on different host then postgres instance for it
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - postgresql
          - key: release
            operator: In
            values:
            - "{{ requiredEnv "RELEASE_NAME" }}-postgresql"
        topologyKey: "kubernetes.io/hostname"
```
