### ISSUE TITLE
[incubator/monochart] Dockercfg name mismatch

### ISSUE THREAD

**Issue by RothAndrew** [cloudposse/charts#266]
## Environment
Chart: incubator/monochart v0.25.0

## What I expect

If I use the following in values.yaml

```
dockercfg:
  enabled: true
  image:
    pullSecret:
      registry: foo
      username: bar
      password: baz
...
```

A secret is created and referenced correctly in a Deployment's pullSecrets

## What I experienced

If, for example, my release name is `foo`, the secret is named `foo-dockercfg` but the imagePullSecrets section in the deployment says

```
imagePullSecrets:
  - name: foo-monochart
```

Since they don't match, the image pull fails.

## Visual Aids

- 
![image](https://user-images.githubusercontent.com/16000938/108127486-4a030e00-7079-11eb-86f5-6d63c099ca42.png)
- 
![image](https://user-images.githubusercontent.com/16000938/108127532-5c7d4780-7079-11eb-9990-aecfb6b72b1f.png)
- 
![image](https://user-images.githubusercontent.com/16000938/108127632-87679b80-7079-11eb-87be-21f09c6de210.png)
- 
![image](https://user-images.githubusercontent.com/16000938/108127779-bf6ede80-7079-11eb-8034-565d754bc694.png)
